# Use root/example as user/password credentials
version: '3.7'

services:
  server:
    build: ./server/
    container_name: mis-ext-server
    ports:
      - 3000:3000
    volumes:
      - ./server/api:/app/api
      - ./server/models:/app/models
      - ./server/app.js:/app/app.js
    command: npm run dev

